-- 0013: privacy salts — user-level random salt for commitment-based balances.
--
-- When GLOMBINT_PRIVACY_MODE=true the vault stores balances against
-- keccak256(user, salt) instead of raw addresses, so external observers
-- cannot query a user's balance by looking up their address.
--
-- This migration creates the user_salts table and adds a salt column to
-- deposit_addresses so the frontend can display the one-time commitment
-- to users.

-- Create the user_salts table mapping a user ID to their random salt.
CREATE TABLE IF NOT EXISTS user_salts (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    salt BYTEA NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Add a salt column to deposit_addresses (optional; kept for reference).
-- The actual commitment is derived from user_salts.user_id + salt.
ALTER TABLE deposit_addresses
    ADD COLUMN IF NOT EXISTS salt BYTEA;

-- Backfill: every user that already has a linked deposit address but no salt
-- row gets a fresh 16-byte random salt. Runs at most once per user thanks to
-- the NOT EXISTS guard, so it is idempotent across re-runs.
--
-- Note: new users get their salt generated by the backend when they link
-- their deposit address (GLOBMINT_PRIVACY_MODE); this block only covers
-- users linked before the privacy upgrade.
INSERT INTO user_salts (user_id, salt, updated_at)
SELECT da.user_id, gen_random_bytes(16), now()
FROM deposit_addresses da
WHERE NOT EXISTS (SELECT 1 FROM user_salts s WHERE s.user_id = da.user_id);

-- Mirror a stored salt into deposit_addresses.salt for reference, but NEVER
-- overwrite an existing deposit_addresses salt with NULL (re-runs against a
-- partially-populated database would otherwise trip the NOT NULL constraint).
UPDATE deposit_addresses da
SET salt = us.salt
FROM user_salts us
WHERE us.user_id = da.user_id
  AND us.salt IS NOT NULL
  AND da.salt IS NULL;