-- 0013: privacy salts — user-level random salt for commitment-based balances.
--
-- When GLOMBINT_PRIVACY_MODE=true the vault stores balances against
-- keccak256(user, salt) instead of raw addresses, so external observers
-- cannot query a user's balance by looking up their address.
--
-- This migration creates the user_salts table and adds a salt column to
-- deposit_addresses so the frontend can display the one-time commitment
-- to users.

-- Create the user_salts table mapping a user ID to their random salt.
CREATE TABLE IF NOT EXISTS user_salts (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    salt BYTEA NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Add a salt column to deposit_addresses (optional; kept for reference).
-- The actual commitment is derived from user_salts.user_id + salt.
ALTER TABLE deposit_addresses
    ADD COLUMN IF NOT EXISTS salt BYTEA;

-- Populate user_salts and deposit_addresses.salt for existing users
-- that already have a linked deposit address. Each user gets a fresh
-- 16-byte random salt stored in the DB.
--
-- Note: this step is a one-off migration. New users will have their salt
-- generated by the backend when they link their deposit address.
UPDATE user_salts
SET salt = deposit_addresses.salt
FROM deposit_addresses
WHERE user_salts.user_id = deposit_addresses.user_id;